name: Black Duck Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  blackduck-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Download Black Duck Detect script
      run: |
        curl -s -o detect.sh https://detect.synopsys.com/detect.sh
        chmod +x detect.sh

    - name: Run Black Duck Detect scan
      env:
        BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
        BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      run: |
        ./detect.sh --blackduck.url=$BLACKDUCK_URL \
                    --blackduck.api.token=$BLACKDUCK_API_TOKEN \
                    --detect.policy.check.fail.on.severity=MEDIUM \
                    --detect.project.name=${{ github.repository }} \
                    --detect.project.version.name=${{ github.sha }} \
                    --detect.tools=BLACKDUCK
