name: DAST Scan with OWASP ZAP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # optional: nightly scan

jobs:
  zap-dast-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run OWASP ZAP Baseline Scan
      run: |
        docker run --rm -v $(pwd):/zap/wrk/:rw \
          -t owasp/zap2docker-stable zap-baseline.py \
          -t ${{ secrets.TARGET_URL }} \
          -r zap_report.html

    - name: Upload ZAP Scan Report
      uses: actions/upload-artifact@v3
      with:
        name: ZAP-DAST-Report
        path: zap_report.html
